QubeWeb/QubeWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dq/',include('dq.urls')),
    path('api/',include('api.urls')),
    path('admin/', admin.site.urls),
]

QubeWeb/api/urls.py
from django.urls import path
from api import views

app_name = 'api'
urlpatterns = [
    # 書籍
    path('v1/patients/', views.patient_list, name='patient_list'),   # 一覧
]

QubeWeb/dq/urls.py
from django.urls import path
from dq import views

app_name = 'dq'
urlpatterns = [
    path('grid/',views.grid, name='grid'),
    path('grid/<int:gridNo>/',views.grid, name='grid'),
    path('appointment/',views.appointment_list, name='appointment_list'),
    path('appointment/<int:patient_id>/',views.appointment_list, name='appointment_list'),
    path('appointment/add/',views.appointment_edit, name='appointment_add'),
    path('appointment/mod/<int:appointment_id>/',views.appointment_edit, name='appointment_mod'),
    path('appointment/del/<int:appointment_id>/',views.appointment_del, name='appointment_del'),
    path('patient/',views.patient_list, name='patient_list'),
    path('patient/add/',views.patient_edit, name='patient_add'),
    path('patient/mod/<int:patient_id>/',views.patient_edit, name='patient_mod'),
    path('patient/del/<int:patient_id>/',views.patient_del, name='patient_del'),
]

QubeWeb/api/models.py
from django.db import models

# Create your models here.

QubeWeb/dq/models.py
from django.db import models

class Patient(models.Model):
    """患者管理用モデル"""
    name = models.CharField('患者名',max_length=255)
    birth = models.DateField('生年月日')
    # age_year = models.IntegerField('年齢_Y')
    # age_month = models.IntegerField('年齢_M')
    # age_day = models.IntegerField('年齢_D')

    def __str__(self):
        return self.name

class Appointment(models.Model):
    """予約管理用モデル"""
    bookDateTime = models.DateTimeField('予約日時')

    #verbose_nameは列名らしい。
    #on_deleteは参照先が消えたときに同時に消すかどうか、患者が消えれば予約も消えていい。
    patient = models.ForeignKey(Patient,verbose_name='患者',related_name='appointments',on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.patient} / {self.bookDateTime}'


# class Setting(models.Model):
#     """設定管理用モデル"""

QubeWeb/dq/forms.py
from django.forms import ModelForm
from dq.models import Appointment, Patient

class AppointmentForm(ModelForm):
    """予約のフォーム"""
    class Meta:
        model = Appointment
        fields = ('bookDateTime','patient',)

class PatientForm(ModelForm):
    """患者のフォーム"""
    class Meta:
        model = Patient
        fields = ('name','birth',)

QubeWeb/api/views.py
import json
from collections import OrderedDict
from django.http import HttpResponse
from dq.models import Appointment, Patient

def render_json_response(request, data, status=None):
    json_str = json.dumps(data, ensure_ascii=False, indent=2)
    callback = request.GET.get('callback')
    if not callback:
        callback = request.POST.get('callback')
    
    if callback:
        json_str = "%s(%s)" % (callback, json_str)
        response = HttpResponse(json_str, content_type='application/javascript; charset=UTF-8', status=status)
    else:
        response = HttpResponse(json_str, content_type='application/json; charset=UTF-8', status=status)
        
    return response

def patient_list(request):
    patients = []
    for patient in Patient.objects.all().order_by('id'):
        appointments = []
        for appointment in patient.appointments.order_by('id'):
            appointment_dict = OrderedDict([
                ('id', appointment.id),
                ('test','test'),
                # ('bookDateTime',appointment.bookDateTime),
            ])
            appointments.append(appointment_dict)

        patient_dict = OrderedDict([
            ('id',patient.id),
            ('name',patient.name),
            ('appointments',appointments),
        ])
        patients.append(patient_dict)

    data = OrderedDict([ ('patient',patients) ])
    return render_json_response(request,data)

QubeWeb/dq/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic.list import ListView

from dq.models import Appointment,Patient
from dq.forms import AppointmentForm,PatientForm

from datetime import datetime, timedelta ,date

def appointment_list(request, patient_id=None):
    # return HttpResponse('予約の一覧')
    is_patient = False
    if patient_id:
        is_patient = True
        patient = get_object_or_404(Patient, pk=patient_id)
        appointments = patient.appointments.all().order_by('id')
    else :
        appointments = Appointment.objects.all().order_by('id')

    return render(request,
    'dq/appointment_list.html',
    {
        'appointments':appointments,
        'is_patient':is_patient,
    })

def appointment_edit(request, appointment_id=None):
    # return HttpResponse('予約の編集')
    if appointment_id:
        appointment = get_object_or_404(Appointment, pk=appointment_id)
    else:
        appointment = Appointment()

    if request.method == 'POST':
        form = AppointmentForm(request.POST,instance=appointment)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.save()
            return redirect('dq:appointment_list')
    else:
        form = AppointmentForm(instance=appointment)

    return render(request, 'dq/appointment_edit.html',dict(form=form, appointment_id=appointment_id))

def appointment_del(request, appointment_id):
    # return HttpResponse('予約の削除')
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    appointment.delete()
    return redirect('dq:appointment_list')

class ApointmentList(ListView):
    """患者が持つ予約のリスト"""
    context_object_name = 'appointments'
    template_name = 'dq/patient_appointments_list.html'
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        patient = get_object_or_404(Patient, pk=kwargs['patient_id'])
        appointments = patient.appointments.all().order_by('id')
        self.object_list = appointments

        context = self.get_context_data(object_list=self.object_list, patient=patient)
        return self.render_to_response(context)

def patient_list(request):
    # return HttpResponse('TEST')
    patients = Patient.objects.all().order_by('id')
    return render(request,
    'dq/patient_list.html',
    {'patients':patients})

def patient_edit(request, patient_id=None):
    # return HttpResponse('TEST')
    if patient_id:
        patient = get_object_or_404(Patient, pk=patient_id)
    else:
        patient = Patient()

    if request.method == 'POST':
        form = PatientForm(request.POST,instance=patient)
        if form.is_valid():
            patient = form.save(commit=False)
            patient.save()
            return redirect('dq:patient_list')
    else:
        form = PatientForm(instance=patient)

    return render(request, 'dq/patient_edit.html',dict(form=form, patient_id=patient_id))

def patient_del(request):
    return HttpResponse('TEST')

def grid(request, gridNo=None):
    today = date.today()
    
    time_str_start = "7:00"
    time_str_end = "23:59"
    time_start = datetime.strptime(time_str_start, '%H:%M')
    time_end = datetime.strptime(time_str_end, '%H:%M')
    time_unit = timedelta(minutes=5) #5分刻み

    time_current = time_start
    times = []
    while time_current <= time_end:
        times.append(time_current.strftime('%H:%M'))
        time_current += time_unit

    dates = []
    for i in range(12):
        date_current = today + timedelta(days=i)
        dates.append({
            'year':date_current.strftime('%y'),
            'month':date_current.strftime('%m'),
            'day':date_current.strftime('%d'),
            'week':date_current.strftime('%a'),
        })
    
    if(gridNo == None):
        template = 'grid.html'
    elif(gridNo == 1):
        template = 'grid.html'
    elif(gridNo == 2):
        template = 'grid2.html'
    elif(gridNo == 3):
        template = 'grid3.html'
        
        
    
    return render(request,
    f'dq/{template}',
    {
        'dates':dates,
        'times':times,
        'cellsOfColumn':times.count,
    })

QubeWeb/dq/templates/dq/appointment_edit.html
{% extends "dq/base.html" %}
{% load bootstrap4 %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">書籍の編集</h4>
    {% if appointment_id %}
    <form action="{% url 'dq:appointment_mod' appointment_id=appointment_id %}" method="post">
    {% else %}
    <form action="{% url 'dq:appointment_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'dq:appointment_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

QubeWeb/dq/templates/dq/appointment_list.html
{% extends "dq/base.html" %}

{% block title %}予約の一覧{% endblock title %}

{% block content %}
    {% if is_patient %}
      <h4 class="mt-4 border-bottom">患者の予約一覧</h4>
    {% else %}
      <h4 class="mt-4 border-bottom">予約の一覧</h4>
    {% endif %}
    <a href="{% url 'dq:appointment_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">予約日</th>
          <th scope="col">患者名</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for appointment in appointments %}
        <tr>
          <th scope="row">{{ appointment.id }}</th>
          <td>{{ appointment.bookDateTime }}</td>
          <td>{{ appointment.patient }}</td>
          <td>
            <a href="{% url 'dq:appointment_mod' appointment_id=appointment.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'dq:appointment_del' appointment_id=appointment.id %}" class="btn btn-outline-danger btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if is_patient %}
      <a href="{% url 'dq:patient_list' %}" class="btn btn-secondary btn-sm">戻る</a>
    {% endif %}
{% endblock content %}

QubeWeb/dq/templates/dq/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'dq/css/bootstrap.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
  <div class="container-fluid m-0 p-0">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'dq/js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'dq/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'dq/js/vue.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

QubeWeb/dq/templates/dq/grid.html
{% extends "dq/base.html" %}
{% load static %}

{% block content %}
<div class="q-apo-grid q-apo-grid-back h-100" data-columns="{{ dates|length }}" data-rows="{{ times|length }}">
    <div class="q-apo-col q-apo-header bg-dark">
        <div class="q-apo-cell"></div>
    </div>
    {% for d in dates %}
    <div class="q-apo-col q-apo-header bg-dark">
        <div class="q-apo-cell">
            <div class="text-center text-light">
                <span style="font-size: 0.8em">{{ d.month }}</span>
                <span style="font-size: 0.8em">/</span>
                <span class="font-weight-bold">{{ d.day }}</span>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="q-apo-col">
        {% for t in times %}
            {% if forloop.counter0|divisibleby:12 or forloop.frist %}
                <div class="q-apo-cell q-apo-cell-time-border bg-dark text-center text-light font-weight-bold" data-row="{{ forloop.counter }}">{{ t }}</div>
            {% else %}
                <div class="q-apo-cell bg-dark" data-row="{{ forloop.counter }}"></div>
            {% endif %}
        {% endfor %}
    </div>
    {% for d in dates %}
    <div class="q-apo-col">
        {% for t in times %}
        <div class="q-apo-cell q-apo-cel-main" data-row="{{ forloop.counter }}"></div>
        {% endfor %}
    </div>
    {% endfor %}
</div>

<div class="q-apo-grid q-apo-grid-front" data-columns="{{ dates|length }}" data-rows="{{ times|length }}">
    <div class="q-apo-col"></div>
    {% for d in dates %}
    <div class="q-apo-col">
        <div class="appointment"></div>
    </div>
    {% endfor %}
</div>
{% endblock content %}
{% block extra_js %}
<script>
    const apoGrid = document.querySelector(".q-apo-grid.q-apo-grid-back");
    const apoGridColumns = apoGrid.dataset.columns;
    const apoGridRows = apoGrid.dataset.rows;
    const columns = [];
    columns.push('50px');
    for(let i = 0;i < apoGridColumns;i++){
        columns.push('minmax(100px,1fr)');
    }
    apoGrid.style.gridTemplateColumns = columns.join(' ');
    const apoGridFront = document.querySelector(".q-apo-grid.q-apo-grid-front");
    apoGridFront.style.gridTemplateColumns = columns.join(' ');
    apoGridFront.querySelector(".q-apo-col")


    const grids = Array.from(document.querySelectorAll(".q-apo-grid.q-apo-grid-back .q-apo-cell"));
    grids.forEach(grid => {
        grid.addEventListener('mouseover',e => {
            const index = grids.findIndex(grid => grid === e.target);
            console.log(index);
        });
    });
    // grid.style = {
    //     'gridTemplateColumns': '1fr 1fr'
    // }
    // console.log(grid.style)
</script>
{% endblock extra_js %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'dq/css/grid.css' %}">
{% endblock extra_css %}

QubeWeb/dq/templates/dq/grid2.html
{% extends "dq/base.html" %}
{% load static %}

{% block content %}
<div class="q-grid q-apo-container">
    <section class="q-data" data-columns="{{ dates|length }}" data-rows="{{ times|length }}"></section>
    <div class="q-grid q-apo-header bg-dark text-light">
        <div class="q-apo-col">
            <div class="q-apo-cell"></div>
        </div>
        {% for d in dates %}
        <div class="q-grid q-apo-col q-apo-datestaff" data-column="{{ forloop.counter }}">
            <div class="q-apo-date">
                <div class="q-apo-cell">
                    <span style="font-size: 0.8em">{{ d.month }}</span>
                    <span style="font-size: 0.8em">/</span>
                    <span class="font-weight-bold" style="font-size: 1.4em">{{ d.day }}</span>
                    <span class="badge badge-light">{{ d.week }}</span>
                </div>
            </div>
            <div class="q-apo-staff">
                <div class="q-apo-cell">
                    <span class="font-weight-bold">AAA</span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="q-apo-header-blank"></div>
    <div class="q-grid q-apo-background">
        <div class="q-apo-col">
            {% for t in times %}
                {% if forloop.counter0|divisibleby:12 or forloop.frist %}
                    <div class="q-apo-cell" data-row="{{ forloop.counter }}">
                        <h6>{{ t }}</h6>
                    </div>
                {% else %}
                    <div class="q-apo-cell" data-row="{{ forloop.counter }}"></div>
                {% endif %}
            {% endfor %}
        </div>
        {% for d in dates %}
        <div class="q-apo-col" data-column="{{ forloop.counter }}">
            {% for t in times %}
            <div class="q-apo-cell" data-row="{{ forloop.counter }}"></div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
    <div class="q-grid q-apo-front" hidden>
        <div class="q-apo-col"></div>
        {% for d in dates %}
        <div class="q-apo-col" data-column="{{ forloop.counter }}"></div>
        {% endfor %}
    </div>
    <nav aria-label="ページ送りの実例" class="q-apo-pagination">
        <ul class="pagination bg-light">
          <li class="page-item"><a class="page-link" href="#">前へ</a></li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">次へ</a></li>
        </ul>
    </nav>
</div>
<div class="modal fade" id="staticBackdrop" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title mr-2" id="staticBackdropLabel">予約</h5>
            <div class="btn-group-sm btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-primary active">
                    <input type="radio">再診
                </label>
                <label class="btn btn-outline-secondary">
                    <input type="radio">新規
                </label>
                </div>
            <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form>
                <div class="form-group">
                    <label for="inputAddress2">患者ID</label>
                    <input type="text" class="form-control" id="inputAddress2" placeholder="999999">
                </div>
                <div class="form-group">
                    <label for="inputAddress2">患者ID</label>
                    <input type="text" class="form-control" id="inputAddress2" placeholder="999999">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for="inputEmail4">Eメール</label>
                      <input type="email" class="form-control" id="inputEmail4" placeholder="Eメール">
                    </div>
                    <div class="form-group col-md-6">
                      <label for="inputPassword4">パスワード</label>
                      <input type="password" class="form-control" id="inputPassword4" placeholder="パスワード">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-2">
                      <label for="inputZip">郵便番号</label>
                      <input type="text" class="form-control" id="inputZip">
                    </div>
                    <div class="form-group col-md-4">
                      <label for="inputState">都道府県</label>
                      <select id="inputState" class="form-control">
                        <option selected>選択...</option>
                        <option>...</option>
                      </select>
                    </div>
                    <div class="form-group col-md-6">
                      <label for="inputCity">市町村</label>
                      <input type="text" class="form-control" id="inputCity">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputAddress">住所</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="1丁目2番3号">
                </div>
                <div class="form-group">
                    <label for="inputAddress2">住所2</label>
                    <input type="text" class="form-control" id="inputAddress2" placeholder="マンション名,部屋番号など">
                </div>
            </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">キャンセル</button>
          <button type="button" class="btn btn-primary">保存</button>
        </div>
      </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script>
const apoGrids = document.querySelectorAll(".q-apo-header,.q-apo-background,.q-apo-front");
const apoData = document.querySelector(".q-data");
const dataColumns = apoData.dataset.columns;
const dataRows = apoData.dataset.rows;
const columnsWidth = [];

columnsWidth.push('50px');
for(let i = 0;i < dataColumns;i++){
    columnsWidth.push('minmax(100px,1fr)');
}
apoGrids.forEach(grid => {
    grid.style.gridTemplateColumns = columnsWidth.join(' ');
});

const headerGrid = document.querySelector(".q-apo-header")
const headerMargin = 20;
const headerHeight = headerGrid.getBoundingClientRect().height + headerMargin;
const headerBlank = document.querySelector(".q-apo-header-blank")
headerBlank.style.height = headerHeight + 'px';

const backgroundGrid = document.querySelector(".q-apo-background")
const backgroundGridHeight = backgroundGrid.getBoundingClientRect().height
const frontGrid = document.querySelector(".q-apo-front")
frontGrid.style.height = backgroundGridHeight + 'px';

backgroundGrid.style.top = headerHeight + 'px';
frontGrid.style.top = headerHeight + 'px';

const cells = document.querySelectorAll(".q-grid.q-apo-background .q-apo-cell");
cells.forEach(cell => {
    cell.addEventListener('click',e => {
        const row = e.currentTarget.dataset.row;
        const column = e.currentTarget.parentNode.dataset.column;
        const top = e.currentTarget.getBoundingClientRect().top + window.pageYOffset - headerHeight;
        const max = 5
        const unit = 3;
        const height = (unit * 24) - 4;

        const gridColumn = document.querySelector(".q-apo-background .q-apo-col[data-column='"+column+"']")
        const element = document.createElement('button');
        element.className = 'book btn btn-outline-primary rounded p-0'
        element.textContent = "test"
        element.style.top = top + 'px';
        element.style.height = height + 'px';

        element.type = 'button';
        element.dataset.toggle = 'modal';
        element.dataset.target = '#staticBackdrop';

        gridColumn.appendChild(element)

    });

    const bgColor = "bg-light"
    cell.addEventListener('mouseover',e => {
        e.currentTarget.classList.add(bgColor)
    });
    cell.addEventListener('mouseleave',e => {
        e.currentTarget.classList.remove(bgColor)
    });
});

// window.addEventListener('resize',() => {
//     const windowWidth = window.innerWidth;
//     const cols = document.querySelectorAll('.q-apo-col')
//     cols.forEach(col => {
//         const colRight = col.getBoundingClientRect().right;
//         col.hidden = colRight > windowWidth;
//         if(colRight > windowWidth){

//             // col.classList.add('hide');
//         } else {
//             // col.classList.remove('hide');
//         }
//     });
// });

</script>
{% endblock extra_js %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'dq/css/grid2.css' %}">
{% endblock extra_css %}

QubeWeb/dq/templates/dq/grid3.html
{% extends "dq/base.html" %}
{% load static %}

{% block content %}
<div id="q-apo-container">
    <!-- receive variable -->
    <section class="q-qpo-data" data-columns="{{ dates|length }}" data-rows="{{ times|length }}" hidden></section>

    <!-- days + staffs -->
    <div class="q-apo-header bg-light">
        <div class="q-apo-daystaffs">
            <!-- これが１単位 -->
            <div class="q-apo-col">
                <div class="q-apo-dates">
                    <span class="q-apo-month">7</span>
                    <span>/</span>
                    <span class="q-apo-day">1</span>
                    <span class="q-apo-week">wed</span>
                </div>
                <div class="q-apo-staffs">
                    {% verbatim %}
                    <span>{{ message }}</span>
                    {% endverbatim %}
                </div>
                <headerColumn></headerColumn>
            </div>
        </div>
    </div>

    <!-- main-area -->
    <div class="q-apo-body bg-light">
        <div class="q-apo-back">
            <!-- これが1単位 -->
            <div class="q-apo-col">
                <div class="q-apo-cell"></div>
            </div>
        </div>
        <div class="q-apo-front">
            <!-- これが1単位 -->
            <div class="q-apo-col"></div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'dq/component/headerColumn.vue' %}"></script>
<script>

    const qApoContainer = new Vue({
        el: '#q-apo-container',
        data: {
            message: 'Hello World',
        },
        components: {
            'headerColumn': headerColumn,
        }
    });
</script>
{% endblock extra_js %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'dq/css/grid3.css' %}">
{% endblock extra_css %}

QubeWeb/dq/templates/dq/patient_edit.html
{% extends "dq/base.html" %}
{% load bootstrap4 %}

{% block title %}患者の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">患者の編集</h4>
    {% if patient_id %}
    <form action="{% url 'dq:patient_mod' patient_id=patient_id %}" method="post">
    {% else %}
    <form action="{% url 'dq:patient_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'dq:patient_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

QubeWeb/dq/templates/dq/patient_list.html
{% extends "dq/base.html" %}

{% block title %}予約の一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">患者の一覧</h4>
    <a href="{% url 'dq:patient_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">患者名</th>
          <th scope="col">生年月日</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for patient in patients %}
        <tr>
          <th scope="row">{{ patient.id }}</th>
          <td>{{ patient.name }}</td>
          <td>{{ patient.birth }}</td>
          <td>
            <a href="{% url 'dq:patient_mod' patient_id=patient.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'dq:patient_del' patient_id=patient.id %}" class="btn btn-outline-danger btn-sm">削除</a>
            <a href="{% url 'dq:appointment_list' patient_id=patient.id %}" class="btn btn-outline-info btn-sm">予約の一覧</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}